### ISSUE TITLE
Registering a custom log handler / integration with other backends

### ISSUE THREAD

**Issue by laf0rge** [babelouest/yder#10]
I'm currently experimenting to use libulfius in an application (upcoming USSD gateway part of osmocom.org).  I saw that ulfius uses yder as log backend.  It's great that yder can log to console, syslog and the like.  However, quite a number of more complex programs / frameworks come with their own logging infrastructure.  Normally, one would want to register some kind of call-back function with yder to feed yder log messages into that logging framework.  This way, all parts of a program (including its REST interface)  log via one common framework.

**Comment by babelouest** [comment]
Hello,

As I understand, you'd like to manage yder log messages in a callback function rather than the predefined output, like in [libav logging facility](https://libav.org/documentation/doxygen/master/group__lavu__log.html#ga14034761faf581a8b9ed6ef19b313708) for example.

That's a good idea. Although, to avoid breaking compatibility with existing code, I'd implement it as a new yder function, something like:

```C
int y_init_callback_logs(void (* y_callback_log_message) (const unsigned long type, const char * message, ...));
```

So you'd have to use it with something like:

```C
void my_callback_log_message(void * cls, const unsigned long type, const char * message, ...) {
  // Handle your log messages here
}

void main(void) {
  y_init_logs("Yder callback tests", Y_LOG_MODE_NONE, Y_LOG_LEVEL_ERROR, NULL, "Initializing logs mode: callback, logs level: error");
  y_init_callback_logs(NULL, &my_callback_log_message);
}
```

How about that?

**Comment by babelouest** [comment]
Can you test the new branch [1.4](https://github.com/babelouest/yder/tree/1.4)?

I added the following function:
```C
int y_set_logs_callback(void (* y_callback_log_message) (void * cls, const char * app_name, const time_t date, const unsigned long level, const char * message),
                        void * cls,
                        const char * message);
```

You can check the new example app [log_callback.c](https://github.com/babelouest/yder/blob/1.4/examples/log_callback.c) for a live test.

**Comment by babelouest** [comment]
@laf0rge , any update on the callback feature?

**Comment by babelouest** [comment]
PR #11 merged in master branch
