### ISSUE TITLE
Tests run only one test

### ISSUE THREAD

**Issue by JohnAZoidberg** [babelouest/yder#13]
There is only one test file but it contains multiple tests. It looks like cmake takes those and splits them up into individual tests. When I run the tests however, I get this output:

```
    Start 1: yder_test                                     
1/1 Test #1: yder_test ........................   Passed    0.01 sec                          
                                                                                                                       
100% tests passed, 0 tests failed out of 1                                                                             
                                                                                                                       
Total Test time (real) =   0.01 sec                                                                                    
```

Is that how it is supposed to look?

**Comment by JohnAZoidberg** [comment]
Have you thought about using the `BUILD_TESTING` flag (see [here](https://cmake.org/cmake/help/v3.7/module/CTest.html)) instead of `BUILD_YDER_TESTING`? Then it's more intuitive to figure out how to enable them :)

**Comment by babelouest** [comment]
The reason why there is on one test is because I'm used to put multiple tests in a single test case, it's a little bit quicker to make and when an error occurs, check interrupts the test case and tells you the line number where it fails.

CMake script uses `ctest` which is not verbose at all, I guess it's by design to.

You can check the test output in the log file created in the folder `<cmake_build_directory>/Testing/Temporary/`

Concerning the flag `BUILD_TESTING`, I it in the [old times](https://github.com/babelouest/yder/blob/5c649e2d8cd475a5df03942a79d166b17fdce0b5/CMakeLists.txt#L112) but it messed up with the the command `download_project`: if cmake downloads a subproject and runs its cmake script, it will pass the arguments you gave him in the first place. I searched fo a way to avoid this but I couldn't find it.

In this case, `BUILD_TESTING` will be passed to [orcania](https://github.com/babelouest/orcania), so `make test` will run orcania tests as well as yder tests. And I prefer having the choice not to. So I changed the option to build the tests in all of my project to be specific for each project: `BUILD_YDER_TESTING`, `BUILD_ORCANIA_TESTING`, `BUILD_HOEL_TESTING`, `BUILD_ULFIUS_TESTING`, etc.

Does this answer your questions?

**Comment by JohnAZoidberg** [comment]
I see. Yes, thank you, that answers my questions.
I expected that that's what's happening to the tests.

Maybe you could give an example in the README for how to run the tests and what a successful test-run looks like :)

**Comment by babelouest** [comment]
I'm not sure adding documentation on how to run the unit tests in the README would be a good idea.
Few users would be interested and it would increase the README size.

I implement the Makefile good practice with the target `make check` supported on the root Makefile and the CMake script option is explained in the [install documentation](https://github.com/babelouest/yder#cmake---multi-architecture).

If you have questions on how I made the tests or the library itself, I'm happy to answer them, but that's not the main goal of the library so I prefer not overwriting the documentation.
