### ISSUE TITLE
Time format customizable

### ISSUE THREAD

**Issue by STeXE89** [babelouest/yder#17]
Give the possibility through definitions to customize the format of the time string.

Thank's

**Comment by babelouest** [comment]
Hello @STeXE89 ,

I've implemented the new feature in the master branch: https://github.com/babelouest/yder/commit/ce77b39ff95b5e9670a5666b1bf6411fed91eb25

**Comment by STeXE89** [comment]
Thank you @babelouest for your work!

I need to set millis, nanos, micros in the log string, with strftime is not possible, can you implement the possibility to set this with system ticks instead strftime?

Thank's.

**Comment by babelouest** [comment]
Hello @STeXE89 ,

Sorry but Yder's goal is to log simple messages for my REST APIs mostly, it was designed to be small, portable and efficient.
Inside it uses `time()` and `strftime()` because they are both present in most systems and libc, they are efficient and use small amounts of resources.

Changing that to be able to log messages with milli or nano precision is not Yder's philosophy.
Also keep in mind that `y_log_message()` is synchronous, so logging with nano or milli precision could be not relevant due to yder's own resource consumption.

I suggest you use [clock_gettime](https://linux.die.net/man/3/clock_gettime) and `struct timespec` to measure events with milliseconds or nanoseconds precision.

**Comment by STeXE89** [comment]
Ok, I understand, thank you very much!
